(setq build-project-dir (expand-file-name "."))
(defun refresh-test-env ()
  (shell-command (concat "cp -f " build-project-dir "/test/org/test-template.org test/org/test.org"))
  (create-file-buffer (concat build-project-dir "/test/org/test-template.org")))
(defun setup-env ()
  (package-install-file (nth 0 (file-expand-wildcards "dist/soji-*.tar")))
  (require 'soji)
  (add-to-list 'org-agenda-files (concat build-project-dir "/test/org"))
  (refresh-test-env))
(setup-env)
